version: '3'
services:
  web:
    build: .
    container_name: ApacheServer
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: MysqlData
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: testuser
      MYSQL_DATABASE: testdb
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
    
